name: Cloud Composer Deployment For Prod. Manual tag trigger. 

on:
  push:
    - main

jobs:
  dags_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: test
        runs: bash ../test.sh
