name: Cloud Composer Deployment For Prod. Manual tag trigger. 

on:
  push:
    branches: 
      - main

jobs:
  dags_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: bash ../../test.sh
